In [197]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# for linear regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
#clustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


In [198]:
df =  pd.read_csv('C:\\Users\\HP\\Documents\\diabetes.csv')

In [199]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [200]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [201]:
df.shape

(768, 9)

In [202]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [203]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [205]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [206]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [207]:
x= df.drop('Outcome', axis=1)

In [208]:
y= df['Outcome']

In [209]:
scale= StandardScaler()

In [210]:
x= scale.fit_transform(x)

In [211]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, random_state=42)

In [212]:
x_test.shape

(154, 8)

# machine learning

In [214]:
# logistic regression
log= LogisticRegression()

In [215]:
log.fit(x_train, y_train)

LogisticRegression()

In [216]:
logpred= log.predict(x_test)

In [217]:
logpred [:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [218]:
logacc= accuracy_score(y_test, logpred)*100

In [219]:
logacc

75.32467532467533

In [220]:
logclass= classification_report(y_test, logpred)

In [221]:
print(logclass)

              precision    recall  f1-score   support

           0       0.81      0.80      0.81        99
           1       0.65      0.67      0.66        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154



In [222]:
dtc= DecisionTreeClassifier()

In [223]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [224]:
dtcpred= dtc.predict(x_test)

In [225]:
dtcpred [:10]

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [226]:
dtcacc= accuracy_score(y_test, dtcpred)*100

In [227]:
dtcacc

75.32467532467533

In [228]:
dtclass= classification_report(y_test,dtcpred)

In [229]:
print(dtclass)

              precision    recall  f1-score   support

           0       0.84      0.77      0.80        99
           1       0.63      0.73      0.68        55

    accuracy                           0.75       154
   macro avg       0.74      0.75      0.74       154
weighted avg       0.76      0.75      0.76       154



In [230]:
rfc= RandomForestClassifier()

In [231]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [232]:
rfcpred= rfc.predict(x_test)

In [233]:
rfcpred [:10]

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [234]:
rfclass= classification_report(y_test, rfcpred)

In [235]:
print(rfclass)

              precision    recall  f1-score   support

           0       0.80      0.79      0.80        99
           1       0.63      0.65      0.64        55

    accuracy                           0.74       154
   macro avg       0.72      0.72      0.72       154
weighted avg       0.74      0.74      0.74       154



In [236]:
svm= SVC(probability=True)

In [237]:
svm.fit(x_train, y_train)

SVC(probability=True)

In [238]:
svmpred= svm.predict(x_test)

In [239]:
svmpred [:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [240]:
svmacc= accuracy_score(y_test, svmpred)*100

In [241]:
svmacc

72.72727272727273

In [242]:
svmclass= classification_report(y_test, svmpred)

In [243]:
print(svmclass)

              precision    recall  f1-score   support

           0       0.77      0.82      0.79        99
           1       0.63      0.56      0.60        55

    accuracy                           0.73       154
   macro avg       0.70      0.69      0.70       154
weighted avg       0.72      0.73      0.72       154



In [340]:
neighbors= KNeighborsClassifier()

In [344]:
neighbors.fit(x_train, y_train)

KNeighborsClassifier()

In [346]:
neighborspred= neighbors.predict(x_test)

In [348]:
neighborspred [:10]

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0], dtype=int64)

In [356]:
neighborsacc= accuracy_score(y_test, neighborspred)*100

In [358]:
neighborsacc

68.83116883116884

In [360]:
voting= VotingClassifier(estimators=[('log', log), ('dtc', dtc), ('rfc', rfc), ('svm', svm), ('neighbor', neighbors)], voting='soft')

In [362]:
voting.fit(x_train, y_train)

VotingClassifier(estimators=[('log', LogisticRegression()),
                             ('dtc', DecisionTreeClassifier()),
                             ('rfc', RandomForestClassifier()),
                             ('svm', SVC(probability=True)),
                             ('neighbor', KNeighborsClassifier())],
                 voting='soft')

In [364]:
votingpred= voting.predict(x_test)

In [366]:
votingpred [:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

In [368]:
votingacc= accuracy_score(y_test, votingpred)*100

In [370]:
votingacc

74.67532467532467

In [372]:
import pickle

In [311]:
pickle.dump(voting, open('diabetesmodel.pkl', 'wb'))

# clustering

In [314]:
x= df[['Pregnancies',	'Glucose',	'BloodPressure',	'SkinThickness',	'Insulin',	'BMI',	'DiabetesPedigreeFunction',	'Age',	'Outcome']]

In [322]:
kmeans= KMeans(n_clusters=9, random_state=42)

In [324]:
kmeans.fit(x)

KMeans(n_clusters=9, random_state=42)

In [326]:
df['cluster']= kmeanspred= kmeans.predict(x)

In [328]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  cluster  
0                     0.627   50        1        5  
1                     0.351   31        0        7  
2                     0.672   32        1        5  
3                     0.167   21        0        8  
4                     2.288   33        1        0

In [336]:
kmeansil= silhouette_score(x, df['cluster'])*100

In [338]:
kmeansil

28.771300360353084